{
 "title": "Prometheus Alertmanager",
 "tags": [
  "prometheus",
  "altermanager"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(alertmanager_build_info)"
   },
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "实例数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(alertmanager_build_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "集群数量",
   "type": "singlestat",
   "description": "Number of peers in the Alertmanager cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_cluster_members{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "实例信息",
   "type": "table",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{instance=~\"$instance\"} * on (instance, cluster) group_left process_start_time_seconds{instance=~\"$instance\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "活跃告警数",
   "type": "singlestat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "抑制报警数",
   "type": "singlestat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "活跃的沉默次数",
   "type": "singlestat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "当前报警",
   "type": "table",
   "description": "Таблица с последними предупреждениями",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(ALERTS{instance=~\"$instance\"} == 1) by (instance,alertname,service,job)",
     "legendFormat": "service: {{service}} environment: {{environment}} instance: {{instance}}  alertname: {{alertname}}   service: {{service}}"
    }
   ]
  },
  {
   "title": "接收告警数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "alertmanager_alerts_received_total{status='firing'}",
     "legendFormat": "接收告警数"
    }
   ]
  },
  {
   "title": "发送告警",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(alertmanager_notifications_total)",
     "legendFormat": "成功发送"
    }
   ]
  },
  {
   "title": "告警屏蔽策略",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alertmanager_silences{instance=~\"$instance\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "当前告警",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{instance=~\"$instance\"}) by (state) ",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "$instance CPU使用",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "$instance 内存使用",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "Limit {{ pod }}"
    }
   ]
  }
 ]
}