{
 "title": "Prometheus Pushgateway Process top",
 "tags": [
  "prometheus ",
  "pushgateway",
  "process"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(cpu_usage{exported_job=~'top'},exported_instance)"
   },
   { "name": "AdhocFilters", "label": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "进程数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cpu_usage{exported_instance =~ \"$instance\"})"
    }
   ]
  },
  {
   "title": "当前CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(cpu_usage{exported_instance =~ \"$instance\"})"
    }
   ]
  },
  {
   "title": "平均CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg(cpu_usage{exported_instance =~ \"$instance\"})"
    }
   ]
  },
  {
   "title": "当前内存使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(memory_usage{exported_instance =~ \"$instance\"})"
    }
   ]
  },
  {
   "title": "平均内存使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(memory_usage{exported_instance =~ \"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(10, cpu_usage{exported_instance =~ \"$instance\"})",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, cpu_usage{exported_instance =~ \"$instance\"})",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "内存 使用率",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(10, memory_usage{exported_instance =~ \"$instance\"})",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "内存 使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, memory_usage{exported_instance =~ \"$instance\"})",
     "legendFormat": "{{process}} {{pid}}"
    }
   ]
  }
 ]
}