version: "3"

services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:v0.107.0-b.13
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"
    ports:
# plain DNS.
      - 53:53/tcp
      - 53:53/udp
# DHCP server.  network_mode: host
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
# HTTPS/DNS-over-HTTPS.
      - 80:80/tcp
      - 443:443/tcp
# AdGuard Home.
      - 3000:3000/tcp
# DNS-over-TLS.
      - 853:853/tcp
# DNS-over-QUIC.
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
# DNSCrypt.
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ./adguardhome_data/workdir:/opt/adguardhome/work
      - ./adguardhome_data/confdir:/opt/adguardhome/conf
    restart: unless-stopped