{
 "title": "Cortex Performance",
 "description": "Visualize Cortex Performance\nCortex is a High Available, Horizontally Scalable Prometheus as a Service",
 "tags": [ "cortex" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Metrics Ingested Per Second",
   "type": "singlestat",
   "description": "Number of metrics ingested per second. Note that a metric is essentially one data point in a metric series.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(cortex_distributor_received_samples_total[1m]))"
    }
   ]
  },
  {
   "title": "Cassandra READ Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (\nsum(rate(cortex_cassandra_request_duration_seconds_count{operation=\"SELECT\",status_code=~\"4.*|5.*\"}[5m]))\n/\nsum(rate(cortex_cassandra_request_duration_seconds_count{operation=\"SELECT\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "Total Provisioned Write Capacity",
   "type": "singlestat",
   "description": "DynamoDB Write Capacity Units. AWS charges ~$0.000725 per WCU per hour (US-WEST-1 as of 1/03/19)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cortex_dynamo_table_capacity_units{op=\"write\"})"
    }
   ]
  },
  {
   "title": "Chunk Age (95%)",
   "type": "singlestat",
   "description": "95 Percentile age of chunks stored in ingesters. Ideally we want chunks to last at least 12 hours so that queries on recent data is fast",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(cortex_ingester_chunk_age_seconds_bucket{app=\"ingester\"}) by (le))"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{route=~\"api_prom.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Cassandra WRITE Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (\nsum(rate(cortex_cassandra_request_duration_seconds_count{operation=\"INSERT\",status_code=~\"4.*|5.*\"}[5m]))\n/\nsum(rate(cortex_cassandra_request_duration_seconds_count{operation=\"INSERT\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "Total Provisioned Read Capacity",
   "type": "singlestat",
   "description": "DynamoDB Read Capacity Units. AWS charges ~$0.000125 per WCU per hour (US-WEST-1 as of 1/03/19)",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cortex_dynamo_table_capacity_units{op=\"read\"})"
    }
   ]
  },
  {
   "title": "Read (Query)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Error Rate",
     "type": "graph",
     "description": "Success rate of fulfilled queries (from query-frontend)",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=~\"api_prom.*\",status_code=~\"4.*|5.*\"}[5m]))",
       "legendFormat": "Errors"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=~\"api_prom.*\",status_code=~\"2.*\"}[5m]))",
       "legendFormat": "Success"
      }
     ]
    },
    {
     "title": "Query request duration",
     "type": "graph",
     "description": "How long it takes queries to be executed once they reach query-frontend (perceived duration)",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le)(irate(cortex_request_duration_seconds_bucket{route=~\"api_prom.*\"}[5m])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(irate(cortex_request_duration_seconds_bucket{route=~\"api_prom.*\"}[5m])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le)(irate(cortex_request_duration_seconds_bucket{route=~\"api_prom.*\"}[5m])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Querier Read QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{status_code=~\"2.*\", route=~\"api_prom.*\"}[5m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{status_code=~\"4.*\", route=~\"api_prom.*\"}[5m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{status_code=~\"5.*\", route=~\"api_prom.*\"}[5m]))",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Queued Queries",
     "type": "singlestat",
     "description": "Queries in the queue for query-frontend. If this reaches 100, new query requests will be dropped with a HTTP 429 response",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cortex_query_frontend_queue_length{app=\"query-frontend\"})"
      }
     ]
    },
    {
     "title": "Queued Queries Age",
     "type": "graph",
     "description": "The average age of queries in the query-frontend queue",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_query_frontend_queue_duration_seconds_sum[5m])) by (app)",
       "legendFormat": "{{ app }}"
      }
     ]
    },
    {
     "title": "Query Queue Age (95%)",
     "type": "singlestat",
     "description": "Time queries sit in the queue before being executed\n95% of queries begin execution within this time period",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
     "format": "dtdurations",
     "valueName": "avg",
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(cortex_query_frontend_queue_duration_seconds_bucket) by (le))"
      }
     ]
    },
    {
     "title": "Querier Read Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_request_duration_seconds_bucket{route=~\"api_prom.*\"}[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(cortex_request_duration_seconds_bucket{route=~\"api_prom.*\"}[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_request_duration_seconds_bucket{route=~\"api_prom.*\"}[5m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Query Age",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_query_frontend_queue_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(cortex_query_frontend_queue_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_query_frontend_queue_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Chunks per Query",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_chunk_store_chunks_per_query_bucket[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(cortex_chunk_store_chunks_per_query_bucket[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_chunk_store_chunks_per_query_bucket[5m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Index Lookups per Query",
     "type": "graph",
     "description": "relevant for seriesstore",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_chunk_store_index_lookups_per_query_bucket{app=\"querier\"}[5m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(cortex_chunk_store_index_lookups_per_query_bucket{app=\"querier\"}[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_chunk_store_index_lookups_per_query_bucket{app=\"querier\"}[5m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Chunks per Query",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(cortex_chunk_store_chunks_per_query_sum{app=\"querier\"}[5m]))",
       "legendFormat": "Chunks"
      }
     ]
    },
    {
     "title": "Index Lookups per Query",
     "type": "graph",
     "description": "relevant for seriesstore",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(cortex_chunk_store_index_lookups_per_query_sum{app=\"querier\"}[5m]))\n",
       "legendFormat": "Index Lookups"
      }
     ]
    }
   ]
  },
  {
   "title": "Write (Ingestion)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cortex Ingestion Rate (metrics/s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(cortex_distributor_received_samples_total[5m])",
       "legendFormat": "Tenant: {{ user }}"
      },
      {
       "expr": "sum(irate(cortex_distributor_received_samples_total[5m]))",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Ingester Flush Queue Length",
     "type": "graph",
     "description": "Number of samples in ingesters to be flushed",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(cortex_ingester_flush_queue_length{app=\"ingester\"}[2m]))",
       "legendFormat": "All Ingesters"
      },
      {
       "expr": "avg_over_time(cortex_ingester_flush_queue_length{app=\"ingester\"}[2m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Distributor WPS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=\"api_prom_push\", status_code=~\"2.*\"}[5m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=\"api_prom_push\", status_code=~\"4.*\"}[5m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=\"api_prom_push\", status_code=~\"5.*\"}[5m]))",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Ingester QPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{status_code=\"success\", route=~\".*Query|.*LabelValues|.*MetricsForLabelMatchers\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{status_code!=\"success\", route=~\".*Query|.*LabelValues|.*MetricsForLabelMatchers\"}[5m]))",
       "legendFormat": "failure"
      }
     ]
    },
    {
     "title": "Ingester WPS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=\"api_prom_push\", status_code=~\"2.*\"}[5m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=\"api_prom_push\", status_code=~\"4.*\"}[5m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(irate(cortex_request_duration_seconds_count{route=\"api_prom_push\", status_code=~\"5.*\"}[5m]))",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_request_duration_seconds_bucket{route=~\".*Query|.*LabelValues|.*MetricsForLabelMatchers\"}[5m])) by (le, route))",
       "legendFormat": "p50 - {{ route }}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_request_duration_seconds_bucket{route=~\".*Query|.*LabelValues|.*MetricsForLabelMatchers\"}[5m])) by (le, route))",
       "legendFormat": "p99 - {{route}}"
      }
     ]
    },
    {
     "title": "Distributor Latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_request_duration_seconds_bucket{route=\"api_prom_push\"}[2m])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(cortex_request_duration_seconds_bucket{route=\"api_prom_push\"}[2m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_request_duration_seconds_bucket{route=\"api_prom_push\"}[2m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Caching (Memcached)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memcache WPS",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 66 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(cortex_cache_request_duration_seconds_count{method=\"memcache.store\"}[2m]))"
      }
     ]
    },
    {
     "title": "Memcache QPS",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 66 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(cortex_cache_request_duration_seconds_count{method=\"memcache-index.fetch\"}[2m]))"
      }
     ]
    },
    {
     "title": "Memcache Write Success Rate [2m]",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (\nsum(irate(cortex_memcache_request_duration_seconds_count{method=~\"Memcache.Put.*\", status_code=~\"5.*\"}[5m]))\n/\nsum(irate(cortex_memcache_request_duration_seconds_count{method=~\"Memcache.Put.*\"}[5m]))\n)",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Memcache Query Success Rate [2m]",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (\nsum(irate(cortex_memcache_request_duration_seconds_count{method=~\"Memcache.Get.*\", status_code=~\"5.*\"}[5m]))\n/\nsum(irate(cortex_memcache_request_duration_seconds_count{method=~\"Memcache.Get.*\"}[5m]))\n)",
       "legendFormat": "2xx"
      }
     ]
    },
    {
     "title": "Memcache Store Latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(cortex_cache_request_duration_seconds_bucket{method=\"memcache.store\"}[2m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cortex_cache_request_duration_seconds_bucket{method=\"memcache.store\"}[2m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cortex_cache_request_duration_seconds_bucket{method=\"memcache.store\"}[2m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Memcache Fetch Latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_cache_request_duration_seconds_bucket{method=\"memcache-index.fetch\"}[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(cortex_cache_request_duration_seconds_bucket{method=\"memcache-index.fetch\"}[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_cache_request_duration_seconds_bucket{method=\"memcache-index.fetch\"}[5m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Ingester Memcached WPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_memcache_request_duration_seconds_count{method=\"Memcache.Put\"}[5m])) by (status_code)",
       "legendFormat": "{{ status_code }}"
      }
     ]
    },
    {
     "title": "Querier Memcached WPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_memcache_request_duration_seconds_count{method=\"Memcache.Put\"name=\"querier\"}[5m])) by (status_code)",
       "legendFormat": "{{ status_code }}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(cortex_cache_hits) by (name, app))/(sum(cortex_cache_fetched_keys) by (name, app))",
       "legendFormat": "{{app}} - {{ name }}"
      }
     ]
    },
    {
     "title": "Time Spent on memcache",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(cortex_cache_request_duration_seconds_bucket{method=~\"memcache.*\"}[5m]))by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cortex_cache_request_duration_seconds_bucket{method=~\"memcache.*\"}[5m]))by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(cortex_cache_request_duration_seconds_bucket{method=~\"memcache.*\"}[5m]))by (le))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "FIFO Cache Writes",
     "type": "graph",
     "description": "PUT: Cache write requests\n\nNew PUT: Cache write requests with new entries\n\nEviction: Cache entries evicted",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(querier_cache_added_total[5m])) by (cache)",
       "legendFormat": "PUT"
      },
      {
       "expr": "sum(irate(querier_cache_added_new_total[5m])) by (cache)",
       "legendFormat": "New PUT"
      },
      {
       "expr": "sum(irate(querier_cache_evicted_total[5m])) by (cache)",
       "legendFormat": "Eviction"
      }
     ]
    },
    {
     "title": "FIFO Cache Reads",
     "type": "graph",
     "description": "Get: Read from cache request\n\nGet Stale: Get for an entry which expired\n\nGet Misses: Get for no valid entry",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(querier_cache_gets_total[5m])) by (cache)",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(irate(querier_cache_stale_gets_total[5m])) by (cache)",
       "legendFormat": "GET (stale)"
      },
      {
       "expr": "sum(irate(querier_cache_misses_total[5m])) by (cache)",
       "legendFormat": "GET (misses)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage (DynamoDB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "DynamoDB Write Quotas",
     "type": "graph",
     "description": "DynamoDB Configured Write Capacity limits for each table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cortex_dynamo_table_capacity_units{op=\"write\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "DynamoDB Read Quotas",
     "type": "graph",
     "description": "DynamoDB Configured Read Capacity limits for each table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cortex_dynamo_table_capacity_units{op=\"read\"}) by (table)",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "WPS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_request_duration_seconds_count{operation=\"DynamoDB.BatchWriteItem\"}[2m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_request_duration_seconds_count{operation=\"DynamoDB.BatchGetItemPages\"}[2m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "Write Errors",
     "type": "graph",
     "description": "Rate of \"ProvisionedThroughputExceededException\" errors per second from AWS APIs",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_failures_total{operation=~\".*Write.*\"}[2m])) by (table, error)",
       "legendFormat": "{{ table }} - {{ error }}"
      }
     ]
    },
    {
     "title": "Read Errors",
     "type": "graph",
     "description": "Rate of \"ProvisionedThroughputExceededException\" errors per second from AWS APIs",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(cortex_dynamo_failures_total{operation=~\".*Query.*\"}[5m])) by (table, error)",
       "legendFormat": "{{ table }} - {{ error }}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(cortex_dynamo_request_duration_seconds_bucket{operation=~\".*Write.*\"}[2m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cortex_dynamo_request_duration_seconds_bucket{operation=~\".*Write.*\"}[2m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(cortex_dynamo_request_duration_seconds_bucket{operation=~\".*Write.*\"}[2m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(cortex_dynamo_request_duration_seconds_bucket{operation=\"DynamoDB.BatchGetItemPages\"}[5m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(cortex_dynamo_request_duration_seconds_bucket{operation=\"DynamoDB.BatchGetItemPages\"}[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(cortex_dynamo_request_duration_seconds_bucket{operation=\"DynamoDB.BatchGetItemPages\"}[5m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "DynamoDB Query Retries",
     "type": "graph",
     "description": "rate of how many times cortex has to re-attempt queries against dynamodb. High values here indicate lots of errors or throttling in the backend, and can result in the query queue increasing.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_query_retry_count_count{operation!~\".*Write.*\"}[1m])) by (operation)",
       "legendFormat": "{{ operation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage (CassandraDB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS",
     "type": "graph",
     "description": "Rate of requests Cortex makes to CassandraDB.",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status_code)(irate(cortex_cassandra_request_duration_seconds_count{operation=\"SELECT\"}[5m]))",
       "legendFormat": "{{ status_code }}"
      }
     ]
    },
    {
     "title": "Query Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 10, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le)(irate(cortex_cassandra_request_duration_seconds_bucket{operation=\"SELECT\"}[5m])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(irate(cortex_cassandra_request_duration_seconds_bucket{operation=\"SELECT\"}[5m])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le)(irate(cortex_cassandra_request_duration_seconds_bucket{operation=\"SELECT\"}[5m])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "WPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status_code)(irate(cortex_cassandra_request_duration_seconds_count{operation=\"INSERT\"}[5m]))",
       "legendFormat": "{{ status_code }}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 10, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le)(irate(cortex_cassandra_request_duration_seconds_bucket{operation=\"INSERT\"}[5m])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le)(irate(cortex_cassandra_request_duration_seconds_bucket{operation=\"INSERT\"}[5m])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le)(irate(cortex_cassandra_request_duration_seconds_bucket{operation=\"INSERT\"}[5m])))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  }
 ]
}